export const countries = [
  { id: 1, label: "Afghanistan" },
  { id: 2, label: "Albania" },
  { id: 3, label: "Algeria" },
  { id: 4, label: "Andorra" },
  { id: 5, label: "Angola" },
  { id: 6, label: "Antigua and Barbuda" },
  { id: 7, label: "Argentina" },
  { id: 8, label: "Armenia" },
  { id: 9, label: "Australia" },
  { id: 10, label: "Austria" },
  { id: 11, label: "Azerbaijan" },
  { id: 12, label: "Bahamas" },
  { id: 13, label: "Bahrain" },
  { id: 14, label: "Bangladesh" },
  { id: 15, label: "Barbados" },
  { id: 16, label: "Belarus" },
  { id: 17, label: "Belgium" },
  { id: 18, label: "Belize" },
  { id: 19, label: "Benin" },
  { id: 20, label: "Bhutan" },
  { id: 21, label: "Bolivia" },
  { id: 22, label: "Bosnia and Herzegovina" },
  { id: 23, label: "Botswana" },
  { id: 24, label: "Brazil" },
  { id: 25, label: "Brunei" },
  { id: 26, label: "Bulgaria" },
  { id: 27, label: "Burkina Faso" },
  { id: 28, label: "Burundi" },
  { id: 29, label: "Cabo Verde" },
  { id: 30, label: "Cambodia" },
  { id: 31, label: "Cameroon" },
  { id: 32, label: "Canada" },
  { id: 33, label: "Central African Republic" },
  { id: 34, label: "Chad" },
  { id: 35, label: "Chile" },
  { id: 36, label: "China" },
  { id: 37, label: "Colombia" },
  { id: 38, label: "Comoros" },
  { id: 39, label: "Congo" },
  { id: 40, label: "Costa Rica" },
  { id: 41, label: "Croatia" },
  { id: 42, label: "Cuba" },
  { id: 43, label: "Cyprus" },
  { id: 44, label: "Czechia" },
  { id: 45, label: "Denmark" },
  { id: 46, label: "Djibouti" },
  { id: 47, label: "Dominica" },
  { id: 48, label: "Dominican Republic" },
  { id: 49, label: "Ecuador" },
  { id: 50, label: "Egypt" },
  { id: 51, label: "El Salvador" },
  { id: 52, label: "Equatorial Guinea" },
  { id: 53, label: "Eritrea" },
  { id: 54, label: "Estonia" },
  { id: 55, label: "Eswatini" },
  { id: 56, label: "Ethiopia" },
  { id: 57, label: "Fiji" },
  { id: 58, label: "Finland" },
  { id: 59, label: "France" },
  { id: 60, label: "Gabon" },
  { id: 61, label: "Gambia" },
  { id: 62, label: "Georgia" },
  { id: 63, label: "Germany" },
  { id: 64, label: "Ghana" },
  { id: 65, label: "Greece" },
  { id: 66, label: "Grenada" },
  { id: 67, label: "Guatemala" },
  { id: 68, label: "Guinea" },
  { id: 69, label: "Guinea-Bissau" },
  { id: 70, label: "Guyana" },
  { id: 71, label: "Haiti" },
  { id: 72, label: "Holy See" },
  { id: 73, label: "Honduras" },
  { id: 74, label: "Hungary" },
  { id: 75, label: "Iceland" },
  { id: 76, label: "India" },
  { id: 77, label: "Indonesia" },
  { id: 78, label: "Iran" },
  { id: 79, label: "Iraq" },
  { id: 80, label: "Ireland" },
  { id: 81, label: "Israel" },
  { id: 82, label: "Italy" },
  { id: 83, label: "Ivory Coast" },
  { id: 84, label: "Jamaica" },
  { id: 85, label: "Japan" },
  { id: 86, label: "Jordan" },
  { id: 87, label: "Kazakhstan" },
  { id: 88, label: "Kenya" },
  { id: 89, label: "Kiribati" },
  { id: 90, label: "Kuwait" },
  { id: 91, label: "Kyrgyzstan" },
  { id: 92, label: "Laos" },
  { id: 93, label: "Latvia" },
  { id: 94, label: "Lebanon" },
  { id: 95, label: "Lesotho" },
  { id: 96, label: "Liberia" },
  { id: 97, label: "Libya" },
  { id: 98, label: "Liechtenstein" },
  { id: 99, label: "Lithuania" },
  { id: 100, label: "Luxembourg" },
  { id: 101, label: "Madagascar" },
  { id: 102, label: "Malawi" },
  { id: 103, label: "Malaysia" },
  { id: 104, label: "Maldives" },
  { id: 105, label: "Mali" },
  { id: 106, label: "Malta" },
  { id: 107, label: "Marshall Islands" },
  { id: 108, label: "Mauritania" },
  { id: 109, label: "Mauritius" },
  { id: 110, label: "Mexico" },
  { id: 111, label: "Micronesia" },
  { id: 112, label: "Moldova" },
  { id: 113, label: "Monaco" },
  { id: 114, label: "Mongolia" },
  { id: 115, label: "Montenegro" },
  { id: 116, label: "Morocco" },
  { id: 117, label: "Mozambique" },
  { id: 118, label: "Myanmar" },
  { id: 119, label: "Namibia" },
  { id: 120, label: "Nauru" },
  { id: 121, label: "Nepal" },
  { id: 122, label: "Netherlands" },
  { id: 123, label: "New Zealand" },
  { id: 124, label: "Nicaragua" },
  { id: 125, label: "Niger" },
  { id: 126, label: "Nigeria" },
  { id: 127, label: "North Korea" },
  { id: 128, label: "North Macedonia" },
  { id: 129, label: "Norway" },
  { id: 130, label: "Oman" },
  { id: 131, label: "Pakistan" },
  { id: 132, label: "Palau" },
  { id: 133, label: "Palestine State" },
  { id: 134, label: "Panama" },
  { id: 135, label: "Papua New Guinea" },
  { id: 136, label: "Paraguay" },
  { id: 137, label: "Peru" },
  { id: 138, label: "Philippines" },
  { id: 139, label: "Poland" },
  { id: 140, label: "Portugal" },
  { id: 141, label: "Qatar" },
  { id: 142, label: "Romania" },
  { id: 143, label: "Russia" },
  { id: 144, label: "Rwanda" },
  { id: 145, label: "Saint Kitts and Nevis" },
  { id: 146, label: "Saint Lucia" },
  { id: 147, label: "Saint Vincent and the Grenadines" },
  { id: 148, label: "Samoa" },
  { id: 149, label: "San Marino" },
  { id: 150, label: "Sao Tome and Principe" },
  { id: 151, label: "Saudi Arabia" },
  { id: 152, label: "Senegal" },
  { id: 153, label: "Serbia" },
  { id: 154, label: "Seychelles" },
  { id: 155, label: "Sierra Leone" },
  { id: 156, label: "Singapore" },
  { id: 157, label: "Slovakia" },
  { id: 158, label: "Slovenia" },
  { id: 159, label: "Solomon Islands" },
  { id: 160, label: "Somalia" },
  { id: 161, label: "South Africa" },
  { id: 162, label: "South Korea" },
  { id: 163, label: "South Sudan" },
  { id: 164, label: "Spain" },
  { id: 165, label: "Sri Lanka" },
  { id: 166, label: "Sudan" },
  { id: 167, label: "Suriname" },
  { id: 168, label: "Sweden" },
  { id: 169, label: "Switzerland" },
  { id: 170, label: "Syria" },
  { id: 171, label: "Tajikistan" },
  { id: 172, label: "Tanzania" },
  { id: 173, label: "Thailand" },
  { id: 174, label: "Timor-Leste" },
  { id: 175, label: "Togo" },
  { id: 176, label: "Tonga" },
  { id: 177, label: "Trinidad and Tobago" },
  { id: 178, label: "Tunisia" },
  { id: 179, label: "Turkey" },
  { id: 180, label: "Turkmenistan" },
  { id: 181, label: "Tuvalu" },
  { id: 182, label: "Uganda" },
  { id: 183, label: "Ukraine" },
  { id: 184, label: "United Arab Emirates" },
  { id: 185, label: "United Kingdom" },
  { id: 186, label: "United States of America" },
  { id: 187, label: "Uruguay" },
  { id: 188, label: "Uzbekistan" },
  { id: 189, label: "Vanuatu" },
  { id: 190, label: "Vatican City" },
  { id: 191, label: "Venezuela" },
  { id: 192, label: "Vietnam" },
  { id: 193, label: "Yemen" },
  { id: 194, label: "Zambia" },
  { id: 195, label: "Zimbabwe" },
];
